repos:
- hooks:
  - id: trailing-whitespace
  - id: check-yaml
  - id: check-added-large-files
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.4.0
- hooks:
  - args:
    - --config=setup.cfg
    description: wemake-python-styleguide enforcement
    entry: flake8
    id: flake8
    language: python
    name: flake8
    types:
    - python
  repo: local
- hooks:
  - id: autopep8
  repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.5.4
- hooks:
  - entry: autoflake
    id: autoflake
    language: python
    name: autoflake
    require_serial: true
    types:
    - python
  repo: https://github.com/myint/autoflake
  rev: v1.4
- hooks:
  - args:
    - --in-place
    id: docformatter
  repo: https://github.com/myint/docformatter
  rev: v1.3.1
- hooks:
  - args:
    - --in-place
    entry: unify
    id: unify
    language: python
    name: unify
    require_serial: true
    types:
    - python
  repo: https://github.com/myint/unify
  rev: v0.5

